import { FiShield, FiUser } from "react-icons/fi";

export default function DriverCard({ driver, onClick }) {
  return <div className="driver-card" onClick={onClick} role="button" tabIndex={0} onKeyDown={(event) => event.key === "Enter" && onClick()}><div className="driver-photo"><FiUser /></div><div className="driver-card-info"><strong>{driver.name}</strong><span>{driver.vehicle} · {driver.number}</span><small><FiShield /> {driver.badge}</small></div><b className="driver-trust-score">{driver.trust}<small>Trust</small></b></div>;
}

export function DriverDetailsModal({ driver, onClose }) {
  if (!driver) return null;
  return <div className="driver-modal-backdrop" onClick={onClose}><section className="driver-modal" role="dialog" aria-modal="true" aria-label="Driver details" onClick={(event) => event.stopPropagation()}><button className="driver-modal-close" onClick={onClose} aria-label="Close driver details">×</button><div className="driver-modal-header"><div className="driver-photo driver-photo-large"><FiUser /></div><div><span className="eyebrow">Driver profile</span><h2>{driver.name}</h2><p>{driver.vehicle} · {driver.number}</p><span className="driver-badge">{driver.badge}</span></div><strong className="modal-trust-score">{driver.trust}<small>Trust score</small></strong></div><div className="driver-history"><span><strong>{driver.trips}</strong><small>Total trips</small></span><span><strong>{driver.rating}</strong><small>Average rating</small></span><span><strong>{driver.verification}</strong><small>Verification status</small></span></div><h3>Trust Breakdown</h3><div className="trust-breakdown"><span>Identity Verification <b>{driver.verification}</b></span><span>Ride Completion Rate <b>{driver.completion}</b></span><span>Passenger Ratings <b>{driver.rating}</b></span><span>Complaint History <b>{driver.complaints}</b></span><span>Route Adherence <b>{driver.adherence}</b></span><span>Driving Behaviour <b>{driver.behaviour}</b></span></div><div className="driver-insight"><strong>Why This Driver Is Trusted</strong><p>✓ High ride completion rate<br />✓ Excellent passenger feedback<br />✓ Verified identity<br />✓ Low complaint history</p></div></section></div>;
}
